### PR TITLE
Added Laravel 10 support

### PR DESCRIPTION
**Pull request by Plytas**

### CODE REVIEW

**Comment by Plytas** [comment]
Apparently we need to update `gtmassey/period` first.

**Comment by Plytas** [comment]
Opened PR on https://github.com/gtmassey/period/pull/1

**Comment by gtmassey** [comment]
Some tests are not passing, I will take a look at them and make a commit fixing any issues, but since Laravel 10.x isn't officially released yet, I think it's best to wait on this PR.

**Comment by Plytas** [comment]
They are failing because we depend on period package. I already opened a PR for it too https://github.com/gtmassey/period/pull/1.

Once that is merged, actions here should pass too.

There's no need to wait for Laravel 10 release. Lots of other packages are already updating their requirements so they will be ready for Laravel 10 from the moment it releases.

**Review by gtmassey — APPROVED** [review]

**Pull request merged**
